<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-AspNetCoreTemplate-f99fb838-0aad-412c-8c87-cd3a52bb0ebf</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCoreTemplate.Application\AspNetCoreTemplate.Application.csproj" />
    <ProjectReference Include="..\AspNetCoreTemplate.Domain\AspNetCoreTemplate.Domain.csproj" />
    <ProjectReference Include="..\AspNetCoreTemplate.EntityFrameWorkCore\AspNetCoreTemplate.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Middleware\" />
    <Folder Include="Extensions\" />
    <Folder Include="Configuration\" />
  </ItemGroup>

</Project>
